couchbase:
  host: pas-macbook.local
  bucketName: default
  bucketPassword:
  clusterAdminUser: Administrator
  clusterAdminPassword: welcome1
security:
  user:
    name: user
    password: password
